sudo: required
dist: trusty

language: cpp

git:
    depth: 1

before_install:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get update --fix-missing
    - sudo apt-get install -qq
        clang
        bcm_host 
        vcos
        vchiq_arm
        EGL
        GLESv2
        pthread
        rt
        dl
    - sudo apt-get update --fix-missing
    - sudo apt-get update -qq
    - pwd
    - ls -d */
    - cd ..
    - pwd
    - git clone --depth=1 --branch=master https://github.com/Daivuk/onut.git onut
    - pwd
    - ls -d */

compiler:
    - clang

branches:
    only:
        - master

script:
    - cmake .
    - make -j4